const data = {
  userList: [
    {
      _id: "5ef38c4cdd254026e02b85d2",
      index: 0,
      guid: "e5e3d32f-0bc7-4d27-a0e8-592df92b6f4b",
      isActive: true,
      balance: "$1,800.53",
      picture: "http://placehold.it/32x32",
      age: 26,
      name: {
        first: "Brooke",
        last: "Malone",
      },
      company: "SILODYNE",
      email: "brooke.malone@silodyne.biz",
      phone: "+1 (935) 474-2732",
      address: "669 Hanson Place, Winfred, Kentucky, 3754",
      about:
        "Sint mollit nulla esse officia culpa nostrud ex magna proident tempor. Voluptate Lorem eu laborum amet cillum cupidatat nostrud ad. Id excepteur labore eiusmod labore in in. Lorem consectetur reprehenderit velit ut enim. Reprehenderit adipisicing aliquip dolore est eu sit ex. Labore velit esse reprehenderit laboris irure consequat. Enim incididunt nostrud sint excepteur magna do qui et magna nostrud ad cillum in adipisicing.",
      registered: "Sunday, June 3, 2018 7:52 PM",
    },
    {
      _id: "5ef38c4cdb5f1e208843fe0b",
      index: 1,
      guid: "1f9eee61-fba6-4fdf-89a0-33f30e733b28",
      isActive: false,
      balance: "$1,197.78",
      picture: "http://placehold.it/32x32",
      age: 38,
      name: {
        first: "Brittney",
        last: "Espinoza",
      },
      company: "DUFLEX",
      email: "brittney.espinoza@duflex.tv",
      phone: "+1 (881) 516-2713",
      address: "122 Polhemus Place, Summerset, Nevada, 2026",
      about:
        "Ullamco laboris elit qui irure reprehenderit irure in tempor nulla fugiat magna. Veniam fugiat sit cupidatat cillum enim eu deserunt laborum tempor commodo culpa nostrud nostrud. Lorem laborum irure commodo laboris occaecat ea deserunt mollit consequat sint sint voluptate aliquip. Esse aliquip fugiat magna adipisicing occaecat incididunt deserunt elit. Deserunt eiusmod dolore enim qui pariatur magna irure voluptate est ex culpa. Minim id officia voluptate ea Lorem ea sint consequat adipisicing sunt labore dolor.",
      registered: "Saturday, July 27, 2019 8:47 AM",
    },
    {
      _id: "5ef38c4c7f878ccce43a8978",
      index: 2,
      guid: "1c75a980-bd47-4e36-a0c5-c70d26ebcbf0",
      isActive: true,
      balance: "$3,757.09",
      picture: "http://placehold.it/32x32",
      age: 38,
      name: {
        first: "Harding",
        last: "Mccall",
      },
      company: "KNOWLYSIS",
      email: "harding.mccall@knowlysis.me",
      phone: "+1 (876) 413-3260",
      address: "644 Norfolk Street, Madaket, Vermont, 5189",
      about:
        "Eiusmod ullamco anim sunt aliqua in id. Est adipisicing tempor ea duis ea esse fugiat consectetur duis cupidatat ea. Aliquip culpa exercitation ex culpa.",
      registered: "Tuesday, February 17, 2015 6:10 AM",
    },
    {
      _id: "5ef38c4c721002fba606202e",
      index: 3,
      guid: "fab7f9b5-292b-4779-b82b-cf225f8ac0fd",
      isActive: true,
      balance: "$2,356.06",
      picture: "http://placehold.it/32x32",
      age: 20,
      name: {
        first: "Sofia",
        last: "Foster",
      },
      company: "SULTRAX",
      email: "sofia.foster@sultrax.com",
      phone: "+1 (856) 486-3145",
      address: "214 Lester Court, Coultervillle, Minnesota, 1265",
      about:
        "Aliquip amet magna aute aute officia qui. Dolor labore veniam irure dolore ad occaecat eu pariatur quis ex duis do magna. Non quis Lorem culpa enim aute pariatur anim sint laborum deserunt. Amet exercitation veniam consectetur quis esse est qui officia minim amet fugiat. Ut deserunt labore sunt amet nisi qui minim et adipisicing dolore est. Nulla quis nulla sunt tempor occaecat anim elit in.",
      registered: "Wednesday, July 4, 2018 3:07 PM",
    },
    {
      _id: "5ef38c4cbb47572ae00c3655",
      index: 4,
      guid: "53de1ecb-0e6d-4cec-b9c9-52c121eeda64",
      isActive: true,
      balance: "$2,186.04",
      picture: "http://placehold.it/32x32",
      age: 36,
      name: {
        first: "Tamra",
        last: "Watts",
      },
      company: "ZOSIS",
      email: "tamra.watts@zosis.name",
      phone: "+1 (832) 418-2988",
      address: "193 Main Street, Kersey, Illinois, 8253",
      about:
        "Occaecat ipsum pariatur laborum aliquip sint dolore aute incididunt id voluptate tempor culpa consectetur. Sit officia eiusmod aute aliquip magna elit anim ullamco nostrud Lorem voluptate. Ea do sunt pariatur duis esse. Id enim nisi dolor excepteur tempor id culpa. Dolor esse qui voluptate id sit qui. Nulla est adipisicing ullamco tempor officia est nulla consequat proident fugiat do. Aliquip pariatur elit in incididunt minim quis nisi consequat exercitation est fugiat.",
      registered: "Tuesday, February 13, 2018 1:34 AM",
    },
    {
      _id: "5ef38c4cbb272c2dfeddb54f",
      index: 5,
      guid: "d3dc563f-10e5-48c2-b4bb-e115c506d29a",
      isActive: true,
      balance: "$2,028.28",
      picture: "http://placehold.it/32x32",
      age: 28,
      name: {
        first: "Aisha",
        last: "Richards",
      },
      company: "QOT",
      email: "aisha.richards@qot.biz",
      phone: "+1 (981) 425-3219",
      address: "107 Clymer Street, Oasis, Florida, 7599",
      about:
        "Cillum ipsum velit irure exercitation laborum ipsum aliquip commodo consequat excepteur. Occaecat commodo adipisicing duis culpa ullamco qui consequat sunt reprehenderit est amet eu consequat ut. In consectetur sint excepteur Lorem minim anim. Nisi et excepteur anim officia voluptate. Laborum reprehenderit tempor occaecat non quis et quis mollit tempor nostrud consequat mollit.",
      registered: "Saturday, December 10, 2016 9:07 AM",
    },
    {
      _id: "5ef38c4cf284a2a09cbe2ddb",
      index: 6,
      guid: "f7191495-7f00-4092-8711-d886e2344a57",
      isActive: false,
      balance: "$2,120.16",
      picture: "http://placehold.it/32x32",
      age: 32,
      name: {
        first: "Whitney",
        last: "Madden",
      },
      company: "EVENTIX",
      email: "whitney.madden@eventix.us",
      phone: "+1 (889) 484-2417",
      address: "496 Gerald Court, Elrama, South Dakota, 1291",
      about:
        "Anim tempor ut mollit esse est aliquip eiusmod eu culpa. Ut esse est quis sunt est ut pariatur laborum aute commodo consectetur exercitation Lorem do. Eu et irure nostrud non sunt aliquip. Incididunt esse esse occaecat mollit est sint magna ipsum est cupidatat ut sunt minim. Ut dolore nulla commodo qui ea minim laborum minim proident nisi elit dolor est.",
      registered: "Sunday, July 3, 2016 2:25 PM",
    },
    {
      _id: "5ef38c4ce7885b921060b8f0",
      index: 7,
      guid: "c59430c0-f122-45b3-bbc9-eb9e84baa487",
      isActive: true,
      balance: "$3,524.19",
      picture: "http://placehold.it/32x32",
      age: 28,
      name: {
        first: "Gilbert",
        last: "Calderon",
      },
      company: "STEELFAB",
      email: "gilbert.calderon@steelfab.net",
      phone: "+1 (993) 463-3428",
      address: "234 Imlay Street, Sussex, New Hampshire, 230",
      about:
        "Labore minim ullamco do cupidatat pariatur pariatur cillum nostrud laboris incididunt sit sit. Amet dolore consectetur laboris laboris ipsum veniam nostrud consequat enim. Cupidatat excepteur aliqua duis incididunt mollit aute fugiat ex aliqua adipisicing sunt pariatur ex consequat. Eu Lorem labore occaecat irure consectetur reprehenderit deserunt minim laboris velit nostrud. Voluptate adipisicing pariatur pariatur commodo fugiat aliquip ipsum dolore consectetur adipisicing nostrud occaecat minim. Aliqua nulla non culpa est sunt reprehenderit aliqua.",
      registered: "Friday, April 5, 2019 4:41 AM",
    },
  ],
};

module.exports = data;
